// Suggested sites that commonly benefit from aggressive mode
export const SUGGESTED_AGGRESSIVE_SITES = [
  'dash.cloudflare.com',
  'developers.cloudflare.com',
  'docs.deno.com',
  'gradio.app',
  'reddit.com',
  'drizzle.team',
  'chatgpt.com',
  'docs.github.com',
  'gemini.google.com',
  'aistudio.google.com',
  'notion.so',
  'linear.app',
  'vercel.com',
  'supabase.com',
  'github.com',
  'mail.google.com',
  'calendar.google.com',
  'drive.google.com',
  'photos.google.com',
  'docs.google.com',
  'sheets.google.com',
  'slides.google.com',
  'meet.google.com',
  'classroom.google.com',
];